In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_csv("supply_chain_data.csv")

In [ ]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), object(9)
memory usage: 18.9+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [ ]:
df['Profit'] = df['Revenue generated'] - df['Costs']

In [ ]:
df.groupby('Transportation modes')['Revenue generated'].sum()

Transportation modes
Air     155735.349650
Rail    164990.417667
Road    159315.232239
Sea      97563.819181
Name: Revenue generated, dtype: float64

In [ ]:
df.groupby('Transportation modes')['Costs'].mean()

Transportation modes
Air     561.712596
Rail    541.747556
Road    553.385988
Sea     417.819148
Name: Costs, dtype: float64

In [ ]:
df['Shrinkage'] = df['Stock levels'] - df['Number of products sold']
print(df['Shrinkage'])

0    -744
1    -683
2      -7
3     -60
4    -866
     ...
95   -657
96   -257
97    -16
98   -860
99   -572
Name: Shrinkage, Length: 100, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
 24  Profit                   100 non-null    float64
 25  Shrinkage                100 non-null    int64
dtypes: float64(7), int64(10), object(9)
memory usage: 20.4+ KB

In [ ]:
df.groupby('Manufacturing lead time')['Production volumes'].mean()

Manufacturing lead time
1     685.000000
2     499.666667
3     474.666667
4     374.600000
5     545.400000
6     476.000000
7     518.250000
8     605.000000
9     750.000000
10    404.750000
11    465.666667
12    516.333333
13    535.000000
14    739.000000
15    867.000000
16    640.666667
17    408.000000
18    564.800000
19    671.000000
20    894.000000
21    480.250000
22    589.000000
23    644.800000
24    742.666667
25    691.000000
26    702.500000
27    849.000000
28    596.857143
29    487.750000
30    661.500000
Name: Production volumes, dtype: float64

In [ ]:
df.groupby('Manufacturing lead time')['Production volumes'].mean()

Manufacturing lead time
1     685.000000
2     499.666667
3     474.666667
4     374.600000
5     545.400000
6     476.000000
7     518.250000
8     605.000000
9     750.000000
10    404.750000
11    465.666667
12    516.333333
13    535.000000
14    739.000000
15    867.000000
16    640.666667
17    408.000000
18    564.800000
19    671.000000
20    894.000000
21    480.250000
22    589.000000
23    644.800000
24    742.666667
25    691.000000
26    702.500000
27    849.000000
28    596.857143
29    487.750000
30    661.500000
Name: Production volumes, dtype: float64

In [ ]:
df.groupby('Production volumes')['Manufacturing costs'].mean()

Production volumes
104    56.766476
109    23.126364
152    55.760493
171    37.700806
173    97.829050
         ...
955     4.465278
963    47.957602
964    19.712993
971    30.688019
985    64.323598
Name: Manufacturing costs, Length: 96, dtype: float64

In [ ]:
df.groupby('Supplier name')['Defect rates'].mean()

Supplier name
Supplier 1    1.803630
Supplier 2    2.362750
Supplier 3    2.465786
Supplier 4    2.337397
Supplier 5    2.665408
Name: Defect rates, dtype: float64

In [ ]:
df.groupby('Supplier name').agg({
    'Manufacturing costs': 'mean',
    'Defect rates': 'mean',
    'Lead time': 'mean'
})

               Manufacturing costs  Defect rates  Lead time
Supplier name
Supplier 1               45.254027      1.803630  14.777778
Supplier 2               41.622514      2.362750  18.545455
Supplier 3               43.634121      2.465786  20.133333
Supplier 4               62.709727      2.337397  15.222222
Supplier 5               44.768243      2.665408  18.055556

In [ ]:
df['Inspection results'].value_counts()

Inspection results
Pending    41
Fail       36
Pass       23
Name: count, dtype: int64

In [ ]:
supplier_perf = df.groupby('Supplier name').agg({
    'Manufacturing costs': 'mean',
    'Defect rates': 'mean',
    'Lead time': 'mean'
}).reset_index()

supplier_perf['Score'] = (
    supplier_perf['Manufacturing costs'] +
    supplier_perf['Defect rates'] +
    supplier_perf['Lead time']
)

top5 = supplier_perf.nsmallest(5, 'Score')
worst5 = supplier_perf.nlargest(5, 'Score')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
 24  Profit                   100 non-null    float64
 25  Shrinkage                100 non-null    int64
dtypes: float64(7), int64(10), object(9)
memory usage: 20.4+ KB

In [ ]:
df.to_csv("cleaned_supply_chain_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_supply_chain_data.csv")